import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Header from "@/components/header";
import Footer from "@/components/footer";
import "./globals.css";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = "de";
  return (
    <html lang={locale ?? ""}>
      <body className={`${roboto.className} bg-neutral-100 text-black`}>
        <div className=" container bg-white h-full min-h-screen flex flex-col justify-between">
          <div>
            <Header locale={locale ?? ""} />
            {children}
          </div>

          <Footer locale={locale ?? ""} />
        </div>
      </body>
    </html>
  );
}
